/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 프로필 상세 조회 */
        get: operations["getUserProfile"];
        /** 사용자 프로필 수정 */
        put: operations["updateUserProfile"];
        post?: never;
        /** 사용자 프로필 삭제 */
        delete: operations["deleteUserProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 트레이너 프로필 상세 조회 */
        get: operations["getTrainerProfile"];
        /** 트레이너 프로필 수정 */
        put: operations["updateTrainerProfile"];
        post?: never;
        /** 트레이너 프로필 삭제 */
        delete: operations["deleteTrainerProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 후기 수정
         * @description 작성자 본인이 후기의 별점·내용을 수정합니다.
         */
        put: operations["updateReview"];
        post?: never;
        /**
         * 후기 삭제
         * @description 작성자 본인이 후기를 삭제합니다.
         */
        delete: operations["deleteReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/{roomId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["markAsRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 프로필 목록 조회 */
        get: operations["getUserProfiles"];
        put?: never;
        /** 사용자 프로필 등록 */
        post: operations["createUserProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 트레이너 목록 조회 및 필터링 */
        get: operations["getTrainerProfiles"];
        put?: never;
        /** 트레이너 프로필 등록 */
        post: operations["createTrainerProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 후기 작성
         * @description 매칭 완료 후 트레이너에게 후기와 별점을 작성합니다.
         */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getChatRooms"];
        put?: never;
        post: operations["getOrCreateChatRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMyInfo"];
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 사용자 프로필 조회 */
        get: operations["getMyUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 트레이너 프로필 조회 */
        get: operations["getMyTrainerProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/trainer/{trainerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 트레이너별 후기 목록 조회
         * @description 특정 트레이너가 받은 후기 목록을 조회합니다.
         */
        get: operations["getReviewsByTrainer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/trainer/{trainerId}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 트레이너 평점 조회
         * @description 트레이너의 평균 평점, 후기 수, 별점 분포를 조회합니다.
         */
        get: operations["getTrainerRating"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/received": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 받은 후기 조회
         * @description 트레이너가 자신이 받은 후기 목록을 조회합니다.
         */
        get: operations["getReceivedReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내가 작성한 후기 조회
         * @description 로그인한 사용자가 작성한 후기 목록을 조회합니다.
         */
        get: operations["getMyReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/trainers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTrainers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/{roomId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["hideChatRoom"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserProfileUpdateRequest: {
            sports?: string;
            level?: string;
            goal?: string;
        };
        UserProfileResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            memberId?: number;
            nickname?: string;
            profileImage?: string;
            introduction?: string;
            region?: string;
            sports?: string;
            level?: string;
            goal?: string;
        };
        TrainerProfileUpdateRequest: {
            sports?: string;
            lessonType?: string;
            /** Format: int32 */
            price?: number;
            /** Format: int32 */
            careerYears?: number;
        };
        TrainerProfileResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            memberId?: number;
            nickname?: string;
            profileImage?: string;
            introduction?: string;
            region?: string;
            sports?: string;
            lessonType?: string;
            /** Format: int32 */
            price?: number;
            /** Format: int32 */
            careerYears?: number;
        };
        ReviewUpdateRequest: {
            /** Format: int32 */
            rating?: number;
            content: string;
        };
        UserProfileRequest: {
            sports?: string;
            level?: string;
            goal?: string;
        };
        TrainerProfileRequest: {
            sports?: string;
            lessonType?: string;
            /** Format: int32 */
            price?: number;
            /** Format: int32 */
            careerYears?: number;
        };
        ReviewRequest: {
            /** Format: int64 */
            matchingId: number;
            /** Format: int64 */
            trainerId: number;
            /** Format: int32 */
            rating?: number;
            content: string;
        };
        ChatRoomRequest: {
            /** Format: int64 */
            trainerId: number;
            /** Format: int64 */
            userId: number;
        };
        ChatRoomResponseDto: {
            /** Format: int64 */
            chatRoomId?: number;
            /** Format: int64 */
            trainerId?: number;
            trainerName?: string;
            trainerProfile?: string;
            /** Format: int64 */
            userId?: number;
            userName?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastMessageAt?: string;
            lastMessage?: string;
            /** Format: int32 */
            unreadCount?: number;
        };
        SignupRequest: {
            userId: string;
            userName: string;
            password: string;
            nickname: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "USER" | "TRAINER" | "ADMIN";
            phone: string;
        };
        LoginResponse: {
            /** Format: int64 */
            memberId?: number;
            userName?: string;
            role?: string;
            accessToken?: string;
            tokenType?: string;
        };
        LoginRequest: {
            userId: string;
            password: string;
        };
        MemberUpdateRequest: {
            nickname?: string;
            profileImage?: string;
            region?: string;
            introduction?: string;
            phone?: string;
        };
        MemberResponse: {
            /** Format: int64 */
            id?: number;
            userId?: string;
            userName?: string;
            nickname?: string;
            email?: string;
            /** @enum {string} */
            role?: "USER" | "TRAINER" | "ADMIN";
            profileImage?: string;
            region?: string;
            introduction?: string;
            phone?: string;
        };
        ReviewResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            matchingId?: number;
            /** Format: int64 */
            reviewerId?: number;
            reviewerNickname?: string;
            /** Format: int64 */
            trainerId?: number;
            /** Format: int32 */
            rating?: number;
            content?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        TrainerRatingResponse: {
            /** Format: int64 */
            trainerId?: number;
            /** Format: double */
            averageRating?: number;
            /** Format: int64 */
            reviewCount?: number;
            ratingDistribution?: {
                [key: string]: number;
            };
        };
        TrainerSummaryDto: {
            /** Format: int64 */
            id?: number;
            userName?: string;
            profileImage?: string;
        };
        ChatResponseDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            chatRoomId?: number;
            /** Format: int64 */
            senderId?: number;
            message?: string;
            /** Format: date-time */
            sentAt?: string;
            isRead?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    updateUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    deleteUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTrainerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["TrainerProfileResponse"];
                };
            };
        };
    };
    updateTrainerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainerProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["TrainerProfileResponse"];
                };
            };
        };
    };
    deleteTrainerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markAsRead: {
        parameters: {
            query: {
                memberId: number;
            };
            header?: never;
            path: {
                roomId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUserProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["UserProfileResponse"][];
                };
            };
        };
    };
    createUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    getTrainerProfiles: {
        parameters: {
            query?: {
                sport?: string;
                lessonType?: string;
                minPrice?: number;
                maxPrice?: number;
                region?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["TrainerProfileResponse"][];
                };
            };
        };
    };
    createTrainerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainerProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["TrainerProfileResponse"];
                };
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": number;
                };
            };
        };
    };
    getChatRooms: {
        parameters: {
            query: {
                memberId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ChatRoomResponseDto"][];
                };
            };
        };
    };
    getOrCreateChatRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRoomRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ChatRoomResponseDto"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    getMyInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["MemberResponse"];
                };
            };
        };
    };
    updateMyInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["MemberResponse"];
                };
            };
        };
    };
    getMyUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    getMyTrainerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["TrainerProfileResponse"];
                };
            };
        };
    };
    getReviewsByTrainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trainerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ReviewResponse"][];
                };
            };
        };
    };
    getTrainerRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trainerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["TrainerRatingResponse"];
                };
            };
        };
    };
    getReceivedReviews: {
        parameters: {
            query: {
                trainerId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ReviewResponse"][];
                };
            };
        };
    };
    getMyReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ReviewResponse"][];
                };
            };
        };
    };
    getTrainers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["TrainerSummaryDto"][];
                };
            };
        };
    };
    getMessages: {
        parameters: {
            query?: {
                before?: number;
                size?: number;
            };
            header?: never;
            path: {
                roomId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ChatResponseDto"][];
                };
            };
        };
    };
    hideChatRoom: {
        parameters: {
            query: {
                memberId: number;
            };
            header?: never;
            path: {
                roomId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
